#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Apr 02, 2018 03:22:12 PM
import sys

import sentiment
import nbc
import analysis

from tkinter import filedialog
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

#import _support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
#    _support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
#    _support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None

def bow():
    root.filename = filedialog.askopenfilename(initialdir="/", title="Select file", filetypes=(("text files", "*.txt"), ("all files", "*.*")))
    if (root.filename != ""):
        sentiment.func(root.filename)

def nb():
    root.filename = filedialog.askopenfilename(initialdir="/", title="Select file", filetypes=(("text files", "*.txt"), ("all files", "*.*")))
    if (root.filename != ""):
        nbc.func(root.filename)

def analysis():
    analysis.analysis(root)


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font13 = "-family {Segoe UI Emoji} -size 24 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font14 = "-family {Segoe UI} -size 18 -weight normal -slant "  \
            "italic -underline 0 -overstrike 0"
        font15 = "-family {Segoe UI} -size 20 -weight normal -slant "  \
            "italic -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("767x588+650+150")
        top.title("New Toplevel 1")
        top.configure(background="#704ee7")
        top.configure(cursor="hand2")



        self.Message1 = Message(top)
        self.Message1.place(relx=-0.03, rely=0.0, relheight=0.24, relwidth=1.04)
        self.Message1.configure(background="#5aaee0")
        self.Message1.configure(font=font13)
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''SENTIMENT ANALYSIS''')
        self.Message1.configure(width=796)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.08, rely=0.51, height=63, width=246)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#000000")
        self.Button1.configure(cursor="boat")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font14)
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''BAG OF WORDS''')
        self.Button1.configure(width=246)
        self.Button1.configure(command=bow)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.08, rely=0.75, height=63, width=246)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#000000")
        self.Button2.configure(cursor="boat")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font14)
        self.Button2.configure(foreground="#ffffff")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''NAIVE BAYES''')
        self.Button2.configure(width=246)
        self.Button2.configure(command=nb)

        self.Button3 = Button(top)
        self.Button3.place(relx=0.65, rely=0.6, height=63, width=226)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#000000")
        self.Button3.configure(cursor="exchange")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font14)
        self.Button3.configure(foreground="#ffffff")
        self.Button3.configure(highlightbackground="#000000")
        self.Button3.configure(highlightcolor="#ffffff")
        self.Button3.configure(overrelief="ridge")
        self.Button3.configure(pady="0")
        self.Button3.configure(relief=GROOVE)
        self.Button3.configure(text='''ANALYSIS''')
        self.Button3.configure(width=226)
        self.Button3.configure(command=analysis)


        self.Message2 = Message(top)
        self.Message2.place(relx=0.07, rely=0.31, relheight=0.09, relwidth=0.35)
        self.Message2.configure(background="#704ee7")
        self.Message2.configure(font=font15)
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''CLASSIFICATION''')
        self.Message2.configure(width=266)

        self.menubar = Menu(top,font=font9,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()


